/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseMap: typeof import('./src/components/base-map/base-map.vue')['default']
    Components: typeof import('./src/components/map2/components/index.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    LeafletMap: typeof import('./src/components/map/leafletMap.vue')['default']
    LeafletMap1: typeof import('./src/components/map2/components/leafletMap1.vue')['default']
    Map_3D: typeof import('./src/components/echartsMap/map_3D.vue')['default']
    Map2: typeof import('./src/components/map2/map2.vue')['default']
    MapBox: typeof import('./src/components/map-box/map-box.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
